# Generated by Django 3.1.5 on 2021-01-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nursery_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('location', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nursery_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nursery_API.nursery')),
            ],
        ),
        migrations.RemoveField(
            model_name='plants',
            name='name',
        ),
        migrations.AddField(
            model_name='plants',
            name='plant_name',
            field=models.CharField(default='Not', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, unique=True)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=18)),
                ('plant_name', models.ManyToManyField(through='Nursery_API.UserPlant', to='Nursery_API.Plants')),
            ],
        ),
        migrations.AddField(
            model_name='userplant',
            name='plant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nursery_API.plants'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nursery_API.users'),
        ),
        migrations.CreateModel(
            name='NurseryPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nursery_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nursery_API.nursery')),
                ('plant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nursery_API.plants')),
            ],
        ),
        migrations.AddField(
            model_name='nursery',
            name='Plant_name',
            field=models.ManyToManyField(through='Nursery_API.NurseryPlant', to='Nursery_API.Plants'),
        ),
    ]
