# Generated by Django 3.1.5 on 2021-01-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nursery_API', '0003_auto_20210107_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseryplant',
            name='price',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
